# Generated by Django 5.1.7 on 2025-03-28 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('publications', '0001_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGMInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('guest', 'guest'), ('media', 'media'), ('staff', 'staff')], max_length=200)),
                ('company_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('is_valid', models.BooleanField(default=True)),
                ('ref', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Luncheon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('member', 'member'), ('exhibitor', 'exhibitor')], max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuickRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('EVENT', 'EVENT'), ('TRAINING', 'TRAINING')], max_length=100)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitorsAGMRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=300)),
                ('company_address', models.CharField(max_length=300)),
                ('participant', models.JSONField()),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('luncheon_covered_participants', models.IntegerField(default=0)),
                ('boot', models.JSONField()),
                ('is_verified', models.BooleanField(default=False)),
                ('mail_recevied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionBoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('name', models.CharField(max_length=200)),
                ('is_occupied', models.BooleanField(default=False)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.exhibitorsagmregistration')),
            ],
        ),
        migrations.CreateModel(
            name='MembersAGMRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=300)),
                ('company_address', models.CharField(max_length=300)),
                ('participant', models.JSONField()),
                ('is_verified', models.BooleanField(default=False)),
                ('mail_recevied', models.BooleanField(default=False)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OthersAGMRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('exhibitor-participant', 'exhibitor-participant'), ('guest', 'guest'), ('media', 'media'), ('staff', 'staff')], max_length=200)),
                ('company_name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=300)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('file_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
