# Generated by Django 5.1.7 on 2025-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
