# Generated by Django 4.2 on 2023-05-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('trainings', '0001_initial'),
        ('payments', '0002_publicationpayment_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpayment',
            name='file_received',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventTrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('EVENT', 'EVENT'), ('TRAINING', 'TRAINING')], max_length=100)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
