# Generated by Django 5.1.7 on 2025-04-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpayment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.payment'),
        ),
    ]
