# Generated by Django 4.2 on 2023-05-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_is_special_event_is_agm_and_more'),
        ('payments', '0003_publicationpayment_file_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGMRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=300)),
                ('company_address', models.CharField(max_length=300)),
                ('participant_details', models.JSONField()),
                ('is_verified', models.BooleanField(default=False)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
