# Generated by Django 4.2 on 2023-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_agmregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='agmregistration',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
