# Generated by Django 5.1.7 on 2025-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_publicationpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
