# Generated by Django 5.1.7 on 2025-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('remita', 'Remita'), ('interswitch', 'Interswitch')], max_length=50, null=True),
        ),
    ]
