# Generated by Django 4.2 on 2023-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_agminvitation_exhibitionboot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agminvitation',
            name='company_name',
            field=models.CharField(default='Tomation Nigeria', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitorsagmregistration',
            name='mail_recevied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membersagmregistration',
            name='mail_recevied',
            field=models.BooleanField(default=False),
        ),
    ]
