# Generated by Django 5.1.7 on 2025-04-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_amount_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtrainingregistration',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
