# Generated by Django 4.2 on 2023-05-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_special',
            new_name='is_agm',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_type',
        ),
    ]
