# Generated by Django 5.1.7 on 2025-04-22 01:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAndMediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/main/')),
                ('news_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/news/')),
                ('news_title', models.CharField(max_length=300)),
                ('news_description', models.TextField()),
                ('news_link_text', models.CharField(max_length=300)),
                ('publication_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/publications/')),
                ('publication_title', models.CharField(max_length=300)),
                ('publication_description', models.TextField()),
                ('publication_link_text', models.CharField(max_length=300)),
                ('event_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/events/')),
                ('event_title', models.CharField(max_length=300)),
                ('event_description', models.TextField()),
                ('event_link_text', models.CharField(max_length=300)),
                ('report_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/reports/')),
                ('report_title', models.CharField(max_length=300)),
                ('report_description', models.TextField()),
                ('report_link_text', models.CharField(max_length=300)),
                ('gallery_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/gallery/')),
                ('gallery_title', models.CharField(max_length=300)),
                ('gallery_description', models.TextField()),
                ('gallery_link_text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
