# Generated by Django 5.1.7 on 2025-04-23 13:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventandmediacontent',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/media_content/main/'),
        ),
    ]
