# Generated by Django 5.1.7 on 2025-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventandmediacontent_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_current_agm',
            field=models.BooleanField(default=False),
        ),
    ]
