@echo off
setx CLOUDINARY_API_KEY ""
setx CLOUDINARY_API_SECRET ""
setx CLOUDINARY_CLOUD_NAME ""
setx DEBUG_VALUE ""
setx EMAIL_HOST_USER ""
setx PAYSTACK_PUBLIC_KEY ""
setx PAYSTACK_SECRET_KEY ""
setx SECRET_KEY ""
setx SENDINBLUE_KEY ""
setx TRUSTED_ALLOWED_ORIGINS_HOST ""
setx admin_mail ""
setx admin_password ""
setx EMAIL_HOST_NAME ""
setx FLUTTERWAVE_PUBLIC_KEY ""
setx FLUTTERWAVE_SECRET_HASH ""
setx FLUTTERWAVE_SECRET_KEY ""
setx DB_HOST ""
setx DB_PORT ""
setx DEVELOPMENT_ENV ""
echo System environment variables have been unset. Restart required.
