# Generated by Django 4.2 on 2023-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_details_delete_newsparagraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
