# Generated by Django 5.1.7 on 2025-03-28 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/advert/')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'advertisment',
                'verbose_name_plural': 'advertisments',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=400)),
                ('content', models.JSONField()),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('slider_welcome_message', models.CharField(max_length=255)),
                ('slider_vision_message', models.CharField(max_length=255)),
                ('slider_mission_message', models.CharField(max_length=255)),
                ('vision_intro', models.JSONField()),
                ('mission_intro', models.JSONField()),
                ('advocacy_intro', models.JSONField()),
                ('history_intro', models.JSONField()),
                ('why_join_intro', models.JSONField()),
                ('members_intro', models.JSONField()),
                ('slider_image1', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('slider_image2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('slider_image3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('writer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoiningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=300)),
                ('step_list', models.JSONField(blank=True)),
                ('step_description', models.TextField(blank=True, default='')),
                ('step_extras', models.JSONField(blank=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OurMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='A Member of Man', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyJoinMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('REASONS', 'REASONS'), ('OTHERS', 'OTHERS')], max_length=300)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhyWeAreUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('heading', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
