# Generated by Django 5.1.7 on 2025-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='history_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='join_man_image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advocacy_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='history_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='members_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_join_intro',
            field=models.TextField(),
        ),
    ]
