# Generated by Django 4.2 on 2023-04-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyWeAreUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('heading', models.CharField(max_length=300)),
                ('writer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('Slider_welcom_message', models.CharField(max_length=255)),
                ('Slider_vision_message', models.CharField(max_length=255)),
                ('Slider_mission_message', models.CharField(max_length=255)),
                ('vision_intro', models.JSONField()),
                ('mission_intro', models.JSONField()),
                ('advocacy_intro', models.JSONField()),
                ('history_intro', models.JSONField()),
                ('why_join_intro', models.JSONField()),
                ('members_intro', models.JSONField()),
                ('slider_image1', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('slider_image2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('slider_image3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('writer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
