# Generated by Django 4.2 on 2023-04-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_whyweareunique_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Slider_mission_message',
            new_name='slider_mission_message',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='Slider_vision_message',
            new_name='slider_vision_message',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='Slider_welcom_message',
            new_name='slider_welcome_message',
        ),
    ]
