# Generated by Django 5.1.7 on 2025-04-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_homepage_history_image3_homepage_join_man_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='history_image3',
            new_name='history_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='join_man_image3',
            new_name='join_man_image',
        ),
    ]
