# Generated by Django 4.2 on 2023-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_rename_slider_mission_message_homepage_slider_mission_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyweareunique',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
