# Generated by Django 5.1.7 on 2025-04-21 23:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_ourmembersbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinStepBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='')),
            ],
        ),
    ]
