# Generated by Django 4.2 on 2023-05-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_ourmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyweareunique',
            name='writer',
        ),
    ]
