# Generated by Django 5.1.7 on 2025-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_whyjoinbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='advocacy_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='history_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='members_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vision_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_join_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
