# Generated by Django 5.1.7 on 2025-04-10 17:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmcms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmexhibitioncms',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='exhibition_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='save_date_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='venue_text_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmpreviousexhibitionandcompanyimages',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmprogrammecms',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='speaker_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
        migrations.AlterField(
            model_name='agmvenue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/agm/'),
        ),
    ]
