# Generated by Django 5.1.7 on 2025-04-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmcms', '0003_agmexhibitioncms_event_id_agmfaq_event_id_and_more'),
        ('events', '0006_event_is_current_agm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmexhibitioncms',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmfaq',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmpreviousexhibitionandcompanyimages',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmprogrammecms',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmprograms',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmvenue',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
