# Generated by Django 5.1.7 on 2025-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmcms', '0004_alter_agmexhibitioncms_event_id_and_more'),
        ('events', '0006_event_is_current_agm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmexhibitioncms',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmfaq',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmfaq',
            name='header',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='agm_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='countdown_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='exhibition_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='intro_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='intro_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='save_date_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='venue_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmpreviousexhibitionandcompanyimages',
            name='type',
            field=models.CharField(blank=True, choices=[('exhibition', 'exhibition'), ('company', 'company')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agmprogrammecms',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmprograms',
            name='program_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmprograms',
            name='program_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='header',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='intro_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='speaker_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmvenue',
            name='venue_location_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmvenue',
            name='venue_location_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agmprograms',
            constraint=models.UniqueConstraint(condition=models.Q(('program_title__isnull', False), models.Q(('program_title', ''), _negated=True)), fields=('program_title',), name='unique_program_title_nonempty'),
        ),
    ]
