# Generated by Django 5.1.7 on 2025-04-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmcms', '0005_alter_agmexhibitioncms_intro_text_and_more'),
        ('events', '0006_event_is_current_agm'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agmprograms',
            name='unique_program_title_nonempty',
        ),
        migrations.AlterField(
            model_name='agmprograms',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddConstraint(
            model_name='agmprograms',
            constraint=models.UniqueConstraint(condition=models.Q(('program_title__isnull', False), models.Q(('program_title', ''), _negated=True)), fields=('event', 'program_title'), name='unique_program_title_per_event_when_nonempty'),
        ),
    ]
