# Generated by Django 5.1.7 on 2025-04-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmcms', '0007_remove_agmprograms_unique_program_title_per_event_when_nonempty_and_more'),
        ('events', '0006_event_is_current_agm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmfaq',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmpreviousexhibitionandcompanyimages',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmspeakers',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
