# Generated by Django 5.1.7 on 2025-04-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmcms', '0008_alter_agmfaq_event_id_and_more'),
        ('events', '0006_event_is_current_agm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmexhibitioncms',
            name='event_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmhomepagecms',
            name='event_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmprogrammecms',
            name='event_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='agmvenue',
            name='event_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
