# Generated by Django 5.1.7 on 2025-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribetonewsletter',
            name='name',
            field=models.CharField(default='MAN_User', max_length=255),
            preserve_default=False,
        ),
    ]
