# Generated by Django 4.2 on 2023-04-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRCandMPDCLServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('CORE', 'CORE'), ('MRC', 'MRC'), ('MPDCL', 'MPDCL'), ('OTHERS', 'OTHERS')], max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CoreServices',
        ),
        migrations.DeleteModel(
            name='MPDCLServices',
        ),
        migrations.DeleteModel(
            name='MRCServices',
        ),
    ]
