# Generated by Django 5.1.7 on 2025-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscribetonewsletter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('btn_text', models.CharField(max_length=100)),
                ('form_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/newsletter_ui/')),
            ],
            options={
                'verbose_name': 'Newsletter UI Configuration',
                'verbose_name_plural': 'Newsletter UI Configuration',
            },
        ),
    ]
