# Generated by Django 5.1.7 on 2025-04-10 17:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_newsletteruiconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservices',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsletteruiconfig',
            name='form_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/newsletter_ui/'),
        ),
    ]
