# Generated by Django 4.2 on 2023-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_subscribetonewsletter_allservices_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='ref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribetonewsletter',
            name='ref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
