# Generated by Django 4.2 on 2023-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_requestservice_ref_subscribetonewsletter_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservices',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='allservices',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
