# Generated by Django 5.1.7 on 2025-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebanner',
            name='core_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebanner',
            name='mpdcl_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebanner',
            name='mrc_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
