# Generated by Django 4.2 on 2023-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_allservices_image_alter_allservices_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribetonewsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
