# Generated by Django 5.1.7 on 2025-04-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicebanner_core_desc_servicebanner_mpdcl_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
