# Generated by Django 4.2 on 2023-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_requestservice_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
