# Generated by Django 5.1.7 on 2025-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_requestservice_service_requestservice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='type',
            field=models.TextField(blank=True, help_text='Type of service request', null=True),
        ),
    ]
