# Generated by Django 5.1.7 on 2025-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAdvocacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/advocacy/')),
                ('main_achievements', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutAffilliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/affilliate/')),
                ('ops', models.JSONField()),
                ('international_partners', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/')),
                ('history_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/')),
                ('mission_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/')),
                ('vision_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/')),
                ('history_paragraphs', models.JSONField()),
                ('core_values', models.JSONField()),
                ('vision', models.JSONField()),
                ('mission', models.JSONField()),
                ('objectives', models.JSONField()),
                ('extras', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutHowWeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/how-we-work/')),
                ('how_we_work', models.JSONField()),
                ('how_we_work_details', models.JSONField()),
                ('committees', models.JSONField()),
                ('committee_details', models.JSONField()),
                ('adhoc', models.JSONField()),
                ('spvehicles', models.JSONField()),
                ('spgroups', models.JSONField()),
                ('conduct', models.JSONField()),
                ('conduct_listing', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutOurExecutives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('extra_title1', models.CharField(blank=True, max_length=300, null=True)),
                ('extra_title2', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(choices=[('EXECUTIVE', 'EXECUTIVE'), ('BRANCH', 'BRANCH'), ('SECTORAL', 'SECTORAL'), ('SPECIAL_PURPOSE_VEHICLES', 'SPECIAL_PURPOSE_VEHICLES'), ('SPECIAL_PURPOSE_GROUPS', 'SPECIAL_PURPOSE_GROUPS'), ('LIFE_MEMBERS', 'LIFE_MEMBERS'), ('ELECTED_MEMBERS', 'ELECTED_MEMBERS'), ('STRATEGIC_MEMBERS', 'STRATEGIC_MEMBERS')], max_length=100)),
                ('tenor', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutWhereWeOperate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/about/where-we-operate/')),
                ('national_secretariat', models.TextField()),
                ('coorprate_office', models.TextField()),
                ('branch_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutWhereWeOperateBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('manager_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('email', models.JSONField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AboutWhereWeOperateOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.JSONField()),
                ('phone_no', models.JSONField()),
                ('address', models.CharField(max_length=300)),
                ('website', models.URLField()),
            ],
        ),
    ]
