# Generated by Django 5.1.7 on 2025-04-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthistory',
            name='core_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='extras',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='history_paragraphs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='objectives',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='vision',
            field=models.TextField(),
        ),
    ]
