# Generated by Django 4.2 on 2023-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_aboutwhereweoperate_branch_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutadvocacy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aboutaffilliate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aboutcontactus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='abouthistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='abouthowwework',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='aboutcontactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcontactus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-10'),
            preserve_default=False,
        ),
    ]
