# Generated by Django 5.1.7 on 2025-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_alter_abouthistory_core_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutadvocacy',
            name='main_achievements',
            field=models.TextField(),
        ),
    ]
