# Generated by Django 4.2 on 2023-04-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_alter_aboutadvocacy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutadvocacy',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/advocacy/'),
        ),
        migrations.AlterField(
            model_name='aboutaffilliate',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/affilliate/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='history_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='mission_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='vision_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/how-we-work/'),
        ),
        migrations.AlterField(
            model_name='aboutwhereweoperate',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/about/where-we-operate/'),
        ),
    ]
