# Generated by Django 5.1.7 on 2025-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_alter_aboutadvocacy_main_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutaffilliate',
            name='international_partners',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutaffilliate',
            name='ops',
            field=models.TextField(),
        ),
    ]
