# Generated by Django 5.1.7 on 2025-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_alter_aboutaffilliate_international_partners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthowwework',
            name='adhoc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='committee_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='committees',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='conduct',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='conduct_listing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='how_we_work',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='how_we_work_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='spgroups',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='spvehicles',
            field=models.TextField(),
        ),
    ]
