# Generated by Django 4.2 on 2023-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_aboutourexecutives'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutourexecutives',
            name='tenor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
