# Generated by Django 5.1.7 on 2025-04-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_alter_abouthowwework_adhoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutourexecutives',
            name='order_position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
