# Generated by Django 5.1.7 on 2025-04-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_aboutourexecutives_order_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutourexecutives',
            name='order_position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
