# Generated by Django 5.1.7 on 2025-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_alter_aboutourexecutives_order_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutourexecutives',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
