# Generated by Django 5.1.7 on 2025-04-10 17:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0009_alter_aboutourexecutives_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutadvocacy',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/advocacy/'),
        ),
        migrations.AlterField(
            model_name='aboutaffilliate',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/affilliate/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='history_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='mission_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='vision_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/history/'),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/how-we-work/'),
        ),
        migrations.AlterField(
            model_name='aboutourexecutives',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutwhereweoperate',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/about/where-we-operate/'),
        ),
    ]
