# Generated by Django 5.1.7 on 2025-04-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_alter_aboutadvocacy_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutwhereweoperate',
            name='branch_text_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutwhereweoperate',
            name='coorprate_office_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutwhereweoperate',
            name='national_secretariat_header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
