# Generated by Django 5.1.7 on 2025-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0011_aboutwhereweoperate_branch_text_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthowwework',
            name='adhoc_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthowwework',
            name='committees_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthowwework',
            name='conduct_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthowwework',
            name='conduct_listing_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthowwework',
            name='how_we_work_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthowwework',
            name='spgroups_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthowwework',
            name='spvehicles_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='adhoc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='committee_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='committees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='conduct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='conduct_listing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='how_we_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='how_we_work_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='spgroups',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthowwework',
            name='spvehicles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
