# Generated by Django 5.1.7 on 2025-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0012_abouthowwework_adhoc_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontactus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
