# Generated by Django 5.1.7 on 2025-04-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0014_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_entries', to='aboutus.aboutcontactus'),
        ),
    ]
