# Generated by Django 5.1.7 on 2025-04-01 06:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='details',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='title',
        ),
        migrations.AddField(
            model_name='reports',
            name='report_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reports',
            name='link',
            field=models.FileField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/reports/%d/'),
        ),
    ]
