# Generated by Django 4.2 on 2023-04-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='details',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportsParagraph',
        ),
    ]
