# Generated by Django 4.2 on 2023-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reports_details_delete_reportsparagraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='link',
        ),
    ]
