# Generated by Django 5.1.7 on 2025-04-10 17:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_reports_details_remove_reports_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/reports/'),
        ),
    ]
