# Generated by Django 4.2 on 2023-05-08 00:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_reports_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='link',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/reports/%d/'),
        ),
    ]
