# Generated by Django 4.2 on 2023-10-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='banner',
            field=models.ImageField(default=None, null=True, upload_to='sldierbanner/%d/'),
        ),
    ]
