# Generated by Django 5.1.7 on 2025-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='banner',
            field=models.ImageField(default=None, null=True, upload_to='sliderbanner/%Y/'),
        ),
    ]
