# Generated by Django 5.1.7 on 2025-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_homepageslider_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='order_position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
