# Generated by Django 5.1.7 on 2025-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homepageslider_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
