# Generated by Django 5.1.7 on 2025-04-10 17:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homepageslider_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='banner',
            field=models.ImageField(default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='sliderbanner/%Y/'),
        ),
    ]
