# Generated by Django 4.2 on 2023-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('publication_news', 'publication_news'), ('event_training', 'event_training'), ('public_view', 'public_view'), ('registrations_payments', 'registrations_payments'), ('prospective_certificates', 'prospective_certificates'), ('super_user', 'super_user'), ('executive_secretary', 'executive_secretary')], max_length=200),
        ),
    ]
