# Generated by Django 4.2 on 2023-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='training',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('MRC', 'MRC'), ('MPDCL', 'MPDCL'), ('OTHERS', 'OTHERS')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
