# Generated by Django 4.2 on 2023-05-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_remove_training_is_special_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(max_length=100),
        ),
    ]
