# Generated by Django 4.2 on 2023-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/publications/'),
        ),
    ]
