# Generated by Django 4.2 on 2023-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
