# Generated by Django 4.2 on 2023-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_is_paid_publication_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('MCCI', 'MCCI'), ('MAGAZINE', 'MAGAZINE'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=255),
            preserve_default=False,
        ),
    ]
