# Generated by Django 4.2 on 2023-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='details',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
