# Generated by Django 4.2 on 2023-05-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publicationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='link',
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publicationtype'),
        ),
    ]
