# Generated by Django 4.2 on 2023-05-08 00:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_remove_publication_link_alter_publication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/publications/'),
        ),
    ]
