# Generated by Django 4.2 on 2023-05-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_publication_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='type',
        ),
    ]
