# Generated by Django 4.2 on 2023-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpdcl',
            name='renewable_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
