# Generated by Django 5.1.7 on 2025-04-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_sectoralgroup_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectoralgroup',
            name='description',
        ),
    ]
