# Generated by Django 5.1.7 on 2025-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_remove_sectoralgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectoralgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
