# Generated by Django 5.1.7 on 2025-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_sectoralgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdcl',
            name='our_objectives_items',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mpdcl',
            name='who_we_are',
            field=models.TextField(),
        ),
    ]
