# Generated by Django 5.1.7 on 2025-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_mpdcl_our_objectives_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrc',
            name='who_we_are',
            field=models.JSONField(),
        ),
    ]
