# Generated by Django 5.1.7 on 2025-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_mrc_who_we_are'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrc',
            name='objectives',
            field=models.JSONField(),
        ),
    ]
