# Generated by Django 5.1.7 on 2025-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_mrc_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrc',
            name='objectives',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mrc',
            name='who_we_are',
            field=models.TextField(),
        ),
    ]
