# Generated by Django 5.1.7 on 2025-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_mrc_objectives_alter_mrc_who_we_are'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdcl',
            name='our_objectives_items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mpdcl',
            name='who_we_are',
            field=models.JSONField(),
        ),
    ]
