# Generated by Django 5.1.7 on 2025-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_alter_mpdcl_our_objectives_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdcl',
            name='our_objectives_items',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mpdcl',
            name='renewable_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mpdcl',
            name='who_we_are',
            field=models.TextField(),
        ),
    ]
