# Generated by Django 5.1.7 on 2025-04-21 14:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_alter_mpdcl_our_objectives_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpdcl',
            name='banner_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
