# Generated by Django 5.1.7 on 2025-04-21 19:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_mpdcl_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrc',
            name='banner_image',
            field=models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
