# Generated by Django 5.1.7 on 2025-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_mrc_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrcContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_in_touch_header', models.CharField(max_length=255)),
                ('get_in_touch_desc', models.TextField()),
                ('address_header', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('link_text', models.CharField(max_length=255)),
                ('business_hours_header', models.CharField(max_length=255)),
                ('business_hours', models.TextField()),
            ],
            options={
                'verbose_name': 'MRC Contact Page',
                'verbose_name_plural': 'MRC Contact Pages',
            },
        ),
    ]
