# Generated by Django 5.1.7 on 2025-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_mrccontactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrccontactpage',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
