# Generated by Django 5.1.7 on 2025-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_alter_mrccontactpage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrccontactpage',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
