# Generated by Django 5.1.7 on 2025-04-24 03:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_alter_mrccontactpage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorialBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='')),
            ],
        ),
    ]
